# === RawBoost augmentation ===
algo: 3  # Алгоритм аугментации: 0 - нет, 1-3 - отдельные методы, 4-8 - комбинации

# --- LnL_convolutive_noise parameters ---
nBands: 5  # Количество полос notch-фильтра (чем больше, тем сильнее искажение)
minF: 20  # Мин. частота фильтра (Гц)
maxF: 8000  # Макс. частота фильтра (Гц)
minBW: 100  # Мин. ширина полосы фильтра (Гц)
maxBW: 1000  # Макс. ширина полосы фильтра (Гц)
minCoeff: 10  # Мин. число коэффициентов фильтра
maxCoeff: 100  # Макс. число коэффициентов фильтра
minG: 0  # Мин. усиление линейного компонента
maxG: 0  # Макс. усиление линейного компонента
minBiasLinNonLin: 5  # Мин. разница между линейным и нелинейным компонентом
maxBiasLinNonLin: 20  # Макс. разница между линейным и нелинейным компонентом
N_f: 5  # Порядок (не)линейности, 1 = только линейный

# --- ISD_additive_noise parameters ---
P: 10  # Максимум равномерно распределённых семплов (в %)
g_sd: 2  # Параметр усиления (> 0)

# --- SSI_additive_noise parameters ---
SNRmin: 10  # Минимальный SNR для шума
SNRmax: 40  # Максимальный SNR для шума
